name: stagexl
version: 2.2.2
description: A fast and universal 2D rendering engine for HTML5 and Dart.
homepage: http://www.stagexl.org
repository: https://github.com/bp74/StageXL

environment:
  sdk: ^3.0.0

documentation: http://www.stagexl.org/docs/api/index.html

dependencies:
  xml: '>=6.3.0 <7.0.0'

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  dart_flutter_team_lints: any
  test: any
