name: stagexl
version: 1.4.6
description: A fast and universal 2D rendering engine for HTML5 and Dart.
homepage: http://www.stagexl.org

environment:
  sdk: '>=2.10.0 <2.12.0'

documentation: http://www.stagexl.org/docs/api/index.html

dependencies:
  xml:
    git:
      url: https://github.com/renggli/dart-xml.git
      ref: nullsafety

dev_dependencies:
  test: any
  pedantic: any
  build_test: any
  build_runner: any
  build_web_compilers: any
