name: stagexl
version: 1.4.0+1
author: Bernhard Pichler <support@stagexl.org>
description: A fast and universal 2D rendering engine for HTML5 and Dart.
homepage: http://www.stagexl.org

environment:
  sdk: '>=2.0.0 <3.0.0'

documentation: http://www.stagexl.org/docs/api/index.html

dependencies:
  xml: ^3.0.0

dev_dependencies:
  test: ^1.0.0
  build_test: ^0.10.2
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.0+4
  pedantic: ^1.3.0
