name: stagexl
version: 2.3.1-wip
description: A fast and universal 2D rendering engine for HTML5 and Dart.
homepage: https://www.stagexl.org
repository: https://github.com/bp74/StageXL

environment:
  sdk: ^3.5.0

dependencies:
  http: ^1.2.0
  web: ^1.1.1
  xml: '>=6.3.0 <7.0.0'

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  dart_flutter_team_lints: any
  test: any
