name: stagexl
version: 0.12.0+1
author: Bernhard Pichler <support@stagexl.org>
description: A library for graphically rich content like games, based on the Flash API.
homepage: http://www.stagexl.org
environment:
  sdk: '>=1.12.0 <2.0.0'
documentation: http://www.stagexl.org/docs/api/index.html
dependencies:
  browser: any
  xml: any
dev_dependencies:
  test: any
